### ISSUE TITLE
Typo in the Online Editor

### ISSUE THREAD

**Issue by badouralix** [flix/flix.github.io#2]
The backend server on <http://iostream.dk> may return a failure message with a typo in it : 
> Unable to evalaute non-constant top-level definition.

Expected message would be :
> Unable to evaluate non-constant top-level definition.

Steps to reproduce : 
- go to <http://flix.github.io/try/>
- insert this piece of code : 
```flix
def f(xs: List[Int]): Int = match xs with {
    case Nil     => 0
    case x :: xs => x + f(xs)
}

def test: Int = f(Nil)
```
- click on `Run`

**Comment by magnus-madsen** [comment]
Indeed. There is an implicit assumption that the function named "f" is the entry function and that it takes no arguments. You could try:

```
def g(xs: List[Int]): Int = match xs with {
    case Nil     => 0
    case x :: xs => x + g(xs)
}


def f: Int = g(Nil)
```

but we should make it clear that `f` is being called and that it expects zero arguments. Or perhaps rename it to `main`.

**Comment by badouralix** [comment]
Renaming makes the example work :tada:
I like the idea of the entry function named `main`: this way, examples found in the doc would work pretty much out of the box.
