### ISSUE TITLE
(<=) or (==)? Maybe a typo in http://flix.github.io/try/

### ISSUE THREAD

**Issue by JeffreyBenjaminBrown** [flix/flix.github.io#7]
In
```
def leq(e1: Constant, e2: Constant): Bool = match (e1, e2) with {
    case (Bot, _)           => true
    case (Cst(n1), Cst(n2)) => n1 == n2
    case (_, Top)           => true
    case _                  => false
}
```
it looks like `==` should be a `<=`.

**Comment by magnus-madsen** [comment]
Actually the leq function is *not* comparing whether two integers are less than each other, but rather whether the two lattice elements are less than each other. Hence why n1 == n2. 

The function is basically implementing this picture (stolen from Google images)

![image](https://user-images.githubusercontent.com/2287953/32071107-8c43f954-ba8e-11e7-92d7-283d64430a96.png)
